-- CreateEnum
CREATE TYPE "AIProvider" AS ENUM ('OPENAI', 'CLAUDE');

-- CreateEnum
CREATE TYPE "AIFeedbackRating" AS ENUM ('HELPFUL', 'NOT_HELPFUL');

-- CreateEnum
CREATE TYPE "AIMessageRole" AS ENUM ('USER', 'ASSISTANT', 'SYSTEM');

-- CreateEnum
CREATE TYPE "AIKnowledgeCategory" AS ENUM ('PLAYER_GUIDE', 'DEVELOPER_SDK', 'TROUBLESHOOTING', 'FAQ', 'TOURNAMENT', 'WALLET', 'GENERAL');

-- CreateTable
CREATE TABLE "AIConversation" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "sessionId" TEXT NOT NULL,
    "currentPage" TEXT,
    "userRole" "UserRole",
    "title" TEXT,
    "resolved" BOOLEAN NOT NULL DEFAULT false,
    "escalatedToHuman" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AIConversation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AIMessage" (
    "id" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "role" "AIMessageRole" NOT NULL,
    "content" TEXT NOT NULL,
    "provider" "AIProvider",
    "model" TEXT,
    "tokensUsed" INTEGER,
    "responseTimeMs" INTEGER,
    "confidence" DOUBLE PRECISION,
    "knowledgeUsed" TEXT[],
    "hasVoiceInput" BOOLEAN NOT NULL DEFAULT false,
    "hasVoiceOutput" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AIMessage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AIFeedback" (
    "id" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "messageId" TEXT,
    "userId" TEXT,
    "rating" "AIFeedbackRating" NOT NULL,
    "comment" TEXT,
    "wasResolved" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AIFeedback_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AIKnowledgeBase" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "category" "AIKnowledgeCategory" NOT NULL,
    "tags" TEXT[],
    "embedding" DOUBLE PRECISION[],
    "source" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "timesUsed" INTEGER NOT NULL DEFAULT 0,
    "avgHelpfulness" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AIKnowledgeBase_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AILearnedPattern" (
    "id" TEXT NOT NULL,
    "questionPattern" TEXT NOT NULL,
    "category" "AIKnowledgeCategory" NOT NULL,
    "bestResponse" TEXT NOT NULL,
    "responseSource" TEXT,
    "timesAsked" INTEGER NOT NULL DEFAULT 1,
    "successRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalFeedback" INTEGER NOT NULL DEFAULT 0,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "reviewedByHuman" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AILearnedPattern_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AIKnowledgeGap" (
    "id" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "category" "AIKnowledgeCategory",
    "conversationId" TEXT,
    "userRole" "UserRole",
    "currentPage" TEXT,
    "timesAsked" INTEGER NOT NULL DEFAULT 1,
    "needsReview" BOOLEAN NOT NULL DEFAULT true,
    "resolved" BOOLEAN NOT NULL DEFAULT false,
    "resolution" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AIKnowledgeGap_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "AIConversation_userId_idx" ON "AIConversation"("userId");

-- CreateIndex
CREATE INDEX "AIConversation_sessionId_idx" ON "AIConversation"("sessionId");

-- CreateIndex
CREATE INDEX "AIConversation_createdAt_idx" ON "AIConversation"("createdAt");

-- CreateIndex
CREATE INDEX "AIMessage_conversationId_idx" ON "AIMessage"("conversationId");

-- CreateIndex
CREATE INDEX "AIMessage_createdAt_idx" ON "AIMessage"("createdAt");

-- CreateIndex
CREATE INDEX "AIFeedback_conversationId_idx" ON "AIFeedback"("conversationId");

-- CreateIndex
CREATE INDEX "AIFeedback_rating_idx" ON "AIFeedback"("rating");

-- CreateIndex
CREATE INDEX "AIFeedback_createdAt_idx" ON "AIFeedback"("createdAt");

-- CreateIndex
CREATE INDEX "AIKnowledgeBase_category_idx" ON "AIKnowledgeBase"("category");

-- CreateIndex
CREATE INDEX "AIKnowledgeBase_tags_idx" ON "AIKnowledgeBase"("tags");

-- CreateIndex
CREATE INDEX "AIKnowledgeBase_isActive_idx" ON "AIKnowledgeBase"("isActive");

-- CreateIndex
CREATE INDEX "AILearnedPattern_category_idx" ON "AILearnedPattern"("category");

-- CreateIndex
CREATE INDEX "AILearnedPattern_successRate_idx" ON "AILearnedPattern"("successRate");

-- CreateIndex
CREATE INDEX "AILearnedPattern_timesAsked_idx" ON "AILearnedPattern"("timesAsked");

-- CreateIndex
CREATE INDEX "AIKnowledgeGap_needsReview_idx" ON "AIKnowledgeGap"("needsReview");

-- CreateIndex
CREATE INDEX "AIKnowledgeGap_timesAsked_idx" ON "AIKnowledgeGap"("timesAsked");

-- CreateIndex
CREATE INDEX "AIKnowledgeGap_category_idx" ON "AIKnowledgeGap"("category");

-- AddForeignKey
ALTER TABLE "AIMessage" ADD CONSTRAINT "AIMessage_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "AIConversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AIFeedback" ADD CONSTRAINT "AIFeedback_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "AIConversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AIFeedback" ADD CONSTRAINT "AIFeedback_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "AIMessage"("id") ON DELETE SET NULL ON UPDATE CASCADE;
